import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/shared/footer";
import Nav from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto container lg:px-20`}>
        <Nav />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
